export const Notification = {
  GET_USE_NOTIFICATION_REQUEST: "GET_USE_NOTIFICATION_REQUEST",
  GET_USE_NOTIFICATION_SUCCESS: "GET_USE_NOTIFICATION_SUCCESS",
  GET_USE_NOTIFICATION_FAILED: "GET_USE_NOTIFICATION_FAILED",
};

export const Team = {
  GET_TEAM_REQUEST: "GET_TEAM_REQUEST",
  GET_TEAM_SUCCESS: "GET_TEAM_SUCCESS",
  GET_TEAM_FAILED: "GET_TEAM_FAILED",
};

export const HubLocation = {
  GET_TEAM_REQUEST: "GET_TEAM_REQUEST",
  GET_TEAM_SUCCESS: "GET_TEAM_SUCCESS",
  GET_TEAM_FAILED: "GET_TEAM_FAILED",
};

export const Partners = {
  GET_PARTNERS_REQUEST: "GET_PARTNERS_REQUEST",
  GET_PARTNERS_SUCCESS: "GET_PARTNERS_SUCCESS",
  GET_PARTNERS_FAILED: "GET_PARTNERS_FAILED",
};

export const Testimonials = {
  GET_TESTIMONIALS_REQUEST: "GET_TESTIMONIALS_REQUEST",
  GET_TESTIMONIALS_SUCCESS: "GET_TESTIMONIALS_SUCCESS",
  GET_TESTIMONIALS_FAILED: "GET_TESTIMONIALS_FAILED",
};

export const Blogs = {
  GET_BLOGS_REQUEST: "GET_BLOGS_REQUEST",
  GET_BLOGS_SUCCESS: "GET_BLOGS_SUCCESS",
  GET_BLOGS_FAILED: "GET_BLOGS_FAILED",
};

export const ClientProjects = {
  GET_CLIENT_PROJECTS_REQUEST: "GET_CLIENT_PROJECTS_REQUEST",
  GET_CLIENT_PROJECTS_SUCCESS: "GET_CLIENT_PROJECTS_SUCCESS",
  GET_CLIENT_PROJECTS_FAILED: "GET_CLIENT_PROJECTS_FAILED",
};

export const UpcomingEvents = {
  GET_UPCOMING_EVENTS_REQUEST: "GET_UPCOMING_EVENTS_REQUEST",
  GET_UPCOMING_EVENTS_SUCCESS: "GET_UPCOMING_EVENTS_SUCCESS",
  GET_UPCOMING_EVENTS_FAILED: "GET_UPCOMING_EVENTS_FAILED",
};

export const MediaMention = {
  GET_MEDIA_MENTION_REQUEST: "GET_MEDIA_MENTION_REQUEST",
  GET_MEDIA_MENTION_SUCCESS: "GET_MEDIA_MENTION_SUCCESS",
  GET_MEDIA_MENTION_FAILED: "GET_MEDIA_MENTION_FAILED",
};

export const Press = {
  GET_PRESS_REQUEST: "GET_PRESS_REQUEST",
  GET_PRESS_SUCCESS: "GET_PRESS_SUCCESS",
  GET_PRESS_FAILED: "GET_PRESS_FAILED",
};

// export const Media = {
//   GET_MEDIA_REQUEST: 'GET_MEDIA_REQUEST',
//   GET_MEDIA_SUCCESS: 'GET_MEDIA_SUCCESS',
//   GET_MEDIA_FAILED: 'GET_MEDIA_FAILED',
// };

export const HubLocations = {
  GET_HUB_LOCATION_REQUEST: "GET_HUB_LOCATION_REQUEST",
  GET_HUB_LOCATION_SUCCESS: "GET_HUB_LOCATION_SUCCESS",
  GET_HUB_LOCATION_FAILED: "GET_HUB_LOCATION_FAILED",
};

//Post Constant
export const Investors = {
  POST_INVESTORS_REQUEST: "POST_INVESTORS_REQUEST",
  POST_INVESTORS_SUCCESS: "POST_INVESTORS_SUCCESS",
  POST_INVESTORS_FAILED: "POST_INVESTORS_FAILED",
};

export const OpenPosition = {
  GET_OPENPOSITION_REQUEST: "GET_OPENPOSITION_REQUEST",
  GET_OPENPOSITION_SUCCESS: "GET_OPENPOSITION_SUCCESS",
  GET_OPENPOSITION_FAILED: "GET_OPENPOSITION_FAILED",
};

export const Mentors = {
  POST_MENTORS_REQUEST: "POST_MENTORS_REQUEST",
  POST_MENTORS_SUCCESS: "POST_MENTORS_SUCCESS",
  POST_MENTORS_FAILED: "POST_MENTORS_FAILED",
};

export const Founders = {
  POST_FOUNDERS_REQUEST: "POST_FOUNDERS_REQUEST",
  POST_FOUNDERS_SUCCESS: "POST_FOUNDERS_SUCCESS",
  POST_FOUNDERS_FAILED: "POST_FOUNDERS_FAILED",
};

export const RSVPInvitation = {
  POST_RSVP_INVITATION_REQUEST: "POST_RSVP_INVITATION_REQUEST",
  POST_RSVP_INVITATION_SUCCESS: "POST_RSVP_INVITATION_SUCCESS",
  POST_RSVP_INVITATION_FAILED: "POST_RSVP_INVITATION_FAILED",
};

export const FutureMarker = {
  POST_FUTURE_MARKER_REQUEST: "POST_FUTURE_MARKER_REQUEST",
  POST_FUTURE_MARKER_SUCCESS: "POST_FUTURE_MARKER_SUCCESS",
  POST_FUTURE_MARKER_FAILED: "POST_RSVP_INVITATION_FAILED",
};

export const HubForm = {
  POST_HUBFORM_REQUEST: "POST_HUBFORM_REQUEST",
  POST_HUBFORM_SUCCESS: "POST_HUBFORM_SUCCESS",
  POST_HUBFORM_FAILED: "POST_HUBFORM_FAILED",
};

export const PartnersHub = {
  POST_PARTNERSHUB_REQUEST: "POST_PARTNERSHUB_REQUEST",
  POST_PARTNERSHUB_SUCCESS: "POST_PARTNERSHUB_SUCCESS",
  POST_PARTNERSHUB_FAILED: "POST_PARTNERSHUB_FAILED",
};

export const Enrol = {
  POST_ENROL_REQUEST: "POST_ENROL_REQUEST",
  POST_ENROL_SUCCESS: "POST_ENROL_SUCCESS",
  POST_ENROL_FAILED: "POST_ENROL_FAILED",
};

export const StartAProject = {
  POST_START_A_PROJECT_REQUEST: "POST_START_A_PROJECT_REQUEST",
  POST_START_A_PROJECT_SUCCESS: "POST_START_A_PROJECT_SUCCESS",
  POST_START_A_PROJECT_FAILED: "POST_START_A_PROJECT_FAILED",
};

export const Subscribe = {
  POST_SUBSCRIBE_REQUEST: "POST_SUBSCRIBE_REQUEST",
  POST_SUBSCRIBE_SUCCESS: "POST_SUBSCRIBE_SUCCESS",
  POST_SUBSCRIBE_FAILED: "POST_SUBSCRIBE_FAILED",
};

export const SendinBlue = {
  POST_SENDINBLUE_REQUEST: "POST_SENDINBLUE_REQUEST",
  POST_SENDINBLUE_SUCCESS: "POST_SENDINBLUE_SUCCESS",
  POST_SENDINBLUE_FAILED: "POST_SENDINBLUE_FAILED",
};

export const Comment = {
  POST_COMMENT_REQUEST: "POST_COMMENT_REQUEST",
  POST_COMMENT_SUCCESS: "POST_COMMENT_SUCCESS",
  POST_COMMENT_FAILED: "POST_COMMENT_FAILED",
};

export const Connect = {
  POST_CONNECT_TO_US_REQUEST: "POST_CONNECT_TO_US_REQUEST",
  POST_CONNECT_TO_US_SUCCESS: "POST_CONNECT_TO_US_SUCCESS",
  POST_CONNECT_TO_US_FAILED: "POST_CONNECT_TO_US_FAILED",
};

export const Developer = {
  POST_DEVELOPER_REQUEST: "POST_DEVELOPER_REQUEST",
  POST_DEVELOPER_SUCCESS: "POST_DEVELOPER_SUCCESS",
  POST_DEVELOPER_FAILED: "POST_DEVELOPER_FAILED",
};

export const PitchDeck = {
  POST_PITCHDECK_REQUEST: "POST_PITCHDECK_REQUEST",
  POST_PITCHDECK_SUCCESS: "POST_PITCHDECK_SUCCESS",
  POST_PITCHDECK_FAILED: "POST_PITCHDECK_FAILED",
};

export const Application = {
  POST_APPLICATION_REQUEST: "POST_APPLICATION_REQUEST",
  POST_APPLICATION_SUCCESS: "POST_APPLICATION_SUCCESS",
  POST_APPLICATION_FAILED: "POST_APPLICATION_FAILED",
};
